config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :number_of_guests, :price_per_night, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE '%#{@query}%'")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def update
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def edit
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>All our flats</h1>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="flat-card">
            <div class="flat-card-image" style="background-image: url(<%= flat.picture_url %>)"></div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4> <%= flat.name %></h4>
              </div>
              <p> <%= flat.address %> </p>
              <div class="flex">
                <div class="flex-icon">
                  <i class="fas fa-user"></i>
                  <span> <%= flat.number_of_guests %></span>
                </div>
                <div class="flex-icon">
                  <i class="fas fa-euro-sign"></i>
                  <span> <%= flat.price_per_night %></span>
                </div>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to "More info", flat_path(flat) %>
              <a href="">Edit</a>
              <%= link_to "Remove", flat_path(flat), method: :delete %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-offset-sm-3 new-flat-form">
        <h1>Add a new flat</h1>
        <%= simple_form_for @flat do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :picture_url %>
          <%= f.input :number_of_guests %>
          <%= f.input :price_per_night %>
          <%= f.submit "Create flat", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= @flat.picture_url %>)">

</div>


<div class="container margin-top-negative">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <div class="flat-show-card">
        <h1> <%= @flat.name %></h1>
        <p> <%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <p> <%= @flat.description %></p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="flat-show-card">
        <h2>Book this place!</h2>
        <form>
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">From:</div>
              <input type="text" class="form-control" placeholder="12/10/2017">
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">To:</div>
              <input type="text" class="form-control" placeholder="18/10/2017">
            </div>
          </div>
          <button type="submit" class="btn btn-primary btn-block">Book</button>
        </form>
      </div>
      <div class="flat-show-card">
        <h2> Details</h2>
        <div class="flex">
          <div class="flex-icon">
            <i class="fas fa-user"></i>
            <span> <%= @flat.number_of_guests %></span>
          </div>
          <div class="flex-icon">
            <i class="fas fa-euro-sign"></i>
            <span> <%= @flat.price_per_night %></span>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="social-flex">
          <span>Share</span>
          <div class="social-icons">
            <a href=""><i class="fab fa-facebook"></i></a>
            <a href=""><i class="fab fa-twitter-square"></i></a>
            <a href=""><i class="fas fa-envelope-square"></i></a>
            <a href=""><i class="fab fa-pinterest-square"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <%= link_to "Simple Airbnb", flats_path, class: "navbar-brand" %>
      <div class="right-elements">
        <form class="navbar-form">
          <div class="form-group">
            <input type="search" class="form-control" placeholder="Search" name="query" value="<%=params[:query]%>">
          </div>
          <button type="submit" class="btn btn-success">Search</button>
        </form>
        <%= link_to "Add a flat", new_flat_path, class: "btn btn-primary" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>